---
# task for hadenlabs.activemq

- name: Install packages via pip activemq
  become: yes
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when:
    - activemq_pip_dependencies is defined
  with_items: activemq_pip_dependencies
