---
# task for hadenlabs.activemq

- name: Update rc.d defaults
  shell: 'update-rc.d {{ activemq_instance_name }} defaults'

- name: Ensure activemq service is running
  service:
    name: '{{ activemq_instance_name }}'
    state: started
    enabled: yes
