---
# task for hadenlabs.activemq

- name: "Generate /etc/sysconfig/activemq Redhat"
  template:
    src: sysconfig_activemq.j2
    dest: /etc/sysconfig/activemq
    owner: root
    group: root
    mode: 0755

- name: "Generate systemd service file"
  template:
    src: activemq.service.j2
    dest: /etc/systemd/system/activemq.service
    owner: root
    group: root
  when: activemq_systemd is defined

- name: Configure ActiveMQ activemq.xml
  template: src=activemq.xml.j2
            dest=/etc/activemq/activemq.xml
  notify:
    - restart activemq
